### ISSUE TITLE
system theme has wrong theme button displayed

### ISSUE THREAD

**Issue by kenny019** [re-taro/re-taro.dev#180]
when my system theme is dark mode and i visit your website, the dark mode button is still displayed.

![image](https://github.com/re-taro/re-taro.dev/assets/53145291/4f1d26d4-9ff8-463b-8bb5-389879587d90)

when i click it the button changes the sun icon.

how to replicate:
1. set system preference to dark mode
2. incognito mode
3. visit site, local storage theme key is not set to anything

a fix i can think of is to store the user's system preference into the localstorage on page load if they did not have the theme property in localstorage

**Comment by re-taro** [comment]
Thanks! I'm locking to rebuild my portfolio soon! Please check out!
